config/routes.rb
Geodocs::Application.routes.draw do

  get "welcome_again/index"

  get "search/index"

  get "rebuild/make"

  mount Ckeditor::Engine => '/ckeditor'

  resources :pages

  resources :items

  resources :categories

  devise_scope :user do
    get "logout" => "devise/sessions#destroy"
  end

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => "categories#index"

  resources :uploads
  match 'upload' => 'uploads#index'

  get 'rebuild' => 'rebuild#make'

  get 'search' => 'search#index'

  get 'news' => 'welcome_again#index'

  get 'emails_send' => 'emailer#email_send'

  resources :categories do
    collection do
      get :manage
      post :rebuild
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set dependent: :destroy
  include TheSortableTree::Scopes

  attr_accessible :parent_id, :path, :title, :lft, :rgt, :depth

  # belongs_to :parent, :class_name => 'Category', :counter_cache => true
  # has_many :childrens, :class_name => 'Category', :foreign_key => 'parent_id', :dependent => :destroy

  has_many :items, dependent: :destroy

  validates_presence_of :title, :path

  validates_format_of :title, :with => /\A([[:alnum:]]|\ |\-|_)+\z/

  after_save :update_children_paths

  # Business logic

  def all_childrens
    Category.where(id: _all_childrens)
  end

protected

  def update_children_paths
    children.each do |children|
      children.update_attribute :path, File.join(path, children.title)
    end
  end

  def _all_childrens
    result = []
    children.each do |children|
      result.concat(children._all_childrens)
    end
    children_ids.concat(result)
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :category_id, :document, :title

  belongs_to :category

  mount_uploader :document, DocumentUploader

  validates_presence_of :title, :document, :category_id
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates_presence_of :email, :password

  validates_uniqueness_of :email

end

app/controllers/emailer_controller.rb
class EmailerController < ApplicationController
  def email_send
    
    items = Item.where("created_at >= ?", Time.now.beginning_of_day)

    User.all.each do |u|
      UserMailer.new_items(u, items).deliver
    end
    
    flash[:success] = "Emails are successfully sent!"

    redirect_to admin_dashboard_path  

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base
  def destroy
    require 'fileutils'

    @item = Item.find(params[:id])
    FileUtils.rm_rf @item.document.to_s
    @item.destroy

  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base

end

app/controllers/rebuild_controller.rb
class RebuildController < ApplicationController

  def make
    require 'fileutils'

    items = Item.all #items in the db
    categories = Category.all #categories in the db

    #empty array for items
    i_array = Array.new

    #empty array for categories
    c_array = Array.new

    saved = true
    while saved do
      saved = false
      Dir.glob('public/data/**/*/').each do |dirname|
        path = dirname.chop.to_s
        dir_name = path.split('/').last.to_s
        parent_path = path.chomp(dir_name.to_s).chop

        if Category.find_by_path(path).nil?
          #move category  
          new_name = dir_name.gsub(/[^a-zA-Z0-9\_\-\ ]/, '')
          FileUtils.mv(dirname, parent_path + "/" + new_name) if new_name != dir_name
          path = parent_path + "/" + new_name


          parent = Category.find_by_path(parent_path)

          category = Category.new
          category.title = new_name
          category.path = path
          category.parent_id = parent.id if parent

          break if saved = category.save
        end
      end
    end

    #add /public to items path
    items.each do |i|
      i_array << "public" + i.document.to_s
    end


    Dir.glob('public/data/**/*.*').each do |filename|
      new_filename = File.basename(filename).gsub(/[ ,^()&~]/, '_')
      File.rename(filename, File.join(File.dirname(filename), new_filename))
    end

    files = Dir.glob('public/data/**/*.*') #in disk

    @list = files - i_array
    @list.delete_if{ |l| l == 'public/data' }
    @list.each do |l|
      item = Item.new
      item.category_id = Category.find_by_path(File.dirname(l)).id
      item.title = File.basename(l).gsub('_',' ')
      item.document = File.open(File.join(Rails.root, l))

      item.save
    end

    flash[:success] = "Links are successfully rebuilded"

    redirect_to admin_items_path

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    # @search = Item.search(params[:search].presence || {:id_lt => 0})
    # @Items = @search.all
    @search = Item.search(params[:search])

    if params[:search].present?
      category_ids = Category.select(:id).search(params[:search]).to_a.map{ |c| c.id } 
      item_ids = Item.select(:id).search(params[:search]).to_a.map{ |i| i.id } 

      @Items = Item.where{ (id >> my{item_ids}) | (category_id >> my{category_ids}) }
    end

    @searchable = params[:search].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pass_helper.rb
module PassHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/helpers/rebuild_helper.rb
module RebuildHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_again_helper.rb
module WelcomeAgainHelper
end

app/views/categories/sortable/base/_children.html.haml
= content_tag :ol, raw(children)

app/views/categories/sortable/base/_controls.html.haml
-# EDIT
- edit = link_to '', polymorphic_url(opts[:namespace] + [node], :action => :edit), :title => t('.edit_this'), :class => 'button edit'
-# DELETE
- if opts[:has_children]
  - delete   = link_to('', url_for(opts[:namespace] + [node]),
    :title   => t('.delete'),
    :method  => :delete,
    :data    => { :confirm  => t('.delete_confirm') },
    :class   => 'button delete')
- else
  - delete   = link_to('', '#',
    :title   => t('.cant_be_deleted'),
    :onclick => "alert('#{t('.delete_nested_elements')}')",
    :class   => 'button undeleted')
-# OUTPUT
= edit + delete

app/views/categories/sortable/base/_link.html.haml
- title     = "#{node.title} (#{node.items.count + node.descendants.count})"
- handle    = content_tag :i, '', :class => :handle
- link      = link_to(title, url_for(opts[:namespace] + [node]), :title => title, :class => (:active if current_page? (url_for(opts[:namespace] + [node]))))
- controls  = content_tag(:b, controls, :class => :controls)
- element   = handle + controls + link
%div{ :class => "link#{' root' if root}" }= element

app/views/categories/sortable/base/_new.html.haml
- image = image_tag('iconza/blue/add.png', :class => :nested_set_new_image) + ' '
- link  = link_to(image + t('.create'), opts[:new_url])
.nested_set_new= link

app/views/categories/sortable/base/_node.html.haml
%li{ :id => "#{node.send(opts[:id])}_#{opts[:klass]}", :'data-depth' => node.depth }
  = raw render(:partial => "#{opts[:path]}/link", :locals => {:opts => opts, :root => root, :node => node})
  = render(:partial => "#{opts[:path]}/children", :locals => {:opts => opts, :parent => node, :children => children}) unless children.blank?

app/views/categories/sortable/base/_tree.html.haml
.sortable
  = render :partial => "#{opts[:path]}/new", :locals => { :opts => opts }
  - unless tree.empty?
    :javascript
      $(function() {
        sortable             = new TheSortableTree;
        sortable.max_levels  = #{opts[:max_levels]};
        sortable.rebuild_url = "#{url_for(:controller => opts[:klass].pluralize, :action => :rebuild)}";
        sortable.init()
      })

    %ol.ui-sortable.sortable.nested_set{ :id => "#{opts[:klass]}_nested_set" }= raw tree

app/views/categories/tree/base/_children.html.haml
= content_tag :ol, raw(children)

app/views/categories/tree/base/_link.html.haml
= link_to "#{node.title} (#{node.items.count + node.descendants.count})", url_for(opts[:namespace] + [node]), :class => (:active if current_page? (url_for(opts[:namespace] + [node])))

app/views/categories/tree/base/_node.html.haml
%li
  = raw render(:partial => "#{opts[:path]}/link", :locals => {:opts => opts, :root => root, :node => node})
  = render(:partial => "#{opts[:path]}/children", :locals => {:opts => opts, :parent => node, :children => children}) unless children.blank?

app/views/categories/tree/base/_tree.html.haml
.tree
  - unless tree.empty?
    %ol.nested_set= raw tree

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Geodocs
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Geodocs", root_path, :class => "brand"
        .nav-collapse
          %ul.nav
            - if current_user
              %li= link_to "Files", "/categories"
              %li= link_to "Search", search_path
              - if current_user.superadmin?
                %li= link_to "Admin", admin_dashboard_path
          %ul.nav{:class => "pull-right"}
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %b.icon-wrench
                - if current_user
                  = current_user.email
                %b.caret
              %ul.dropdown-menu
                - if current_user
                  %li= link_to "Edit", edit_user_registration_path
                  %li.divider
                  %li= link_to "Log out", logout_path
                - else
                  %li= link_to "Log in", new_user_session_path
    .container-fluid
      .row-fluid
        .span5
          - if current_user
            .well.well-small
              %ul.nav.nav-list
                %li.nav-header
                  %h3 Categories
                - if current_user
                  - if current_user.superadmin?  
                    = sortable_tree Category.nested_set.all, :max_levels => 5, :path => 'categories/sortable/base', :new_url => new_admin_category_path
                  - else
                    = sortable_tree Category.nested_set.all, path: 'categories/tree/base'
        .span7
          = yield